### ISSUE TITLE
Excessive whitespace before references in some citation styles

### ISSUE THREAD

**Issue by Ourous** [zepinglee/citeproc-lua#25] opened 2022-09-22 00:59 UTC
When using some citation styles (Vancouver, IEEE, probably others...) the reference list will be shoved off to the right side of the page (often completely departing the visible document area) by a large quantity of whitespace (LaTeX complains about overfull hboxes).
This can be seen with the project's own example by changing the citation style from APA  to Vancouver.
Attempting to reproduce it using the example with the IEEE style gives me a "Misplaced tab alignment character &.", but commenting lines 20, 44, and 50 will allow it to compile and demonstrate the same issue.

Great project by the way!

**Comment by zepinglee** [comment] 2022-09-22 03:12
Thanks for your feedback! I can reproduce both the whitespace and ampersand bugs.

**Comment by zepinglee** [comment] 2022-09-22 16:12
These bugs occurred since I rewrote much of the Lua module in v0.2.0 and hey should be fixed in f930d58. I'll upload to CTAN in the next few days.

**Closed** 2022-09-23 09:17 UTC
